### ISSUE TITLE
坐标轴

### ISSUE THREAD

**Issue by luoxin1** [LeonardoTech/FunctionalUtilities#15]
接口：
- void setLabel(string label,float x,float y) 设置要显示的标注名称和显示在屏幕的位置
- void setColor(string color, int axis)设置轴的颜色
- void setOriginPoint(float x,float y,float y) 设置轴原点的位置
- void getAxisDirection3D(float& x,float& y,float& z)获得轴在3围中的方向
  @LeonardoTech

**Comment by luoxin1** [comment]
void setLabel(string label,int axis, int stopPosition,float distance) 设置要显示标注显示的位置，距离轴的距离
void setLabelVisible(bool bvisible,int axis);//标注在是否可见
void setColor(string color, int axis)设置轴的颜色
void setOriginPoint(float x,float y,float y) 设置轴原点的位置
void getAxisDirection3D(float& x,float& y,float& z,int axis)获得轴在3围中的方向
void setColorAxisInsideOutside(int axis);设置轴朝里朝外的轴的颜色
@LeonardoTech

**Comment by luoxin1** [comment]
void setLabel( AXISDIRECTION axis,string label) = 0;//设置标注
void setLabelPosition(AXISDIRECTION axis, float x, float y, float z, ) = 0;//设置标注出现的位置
void setColor(AXISDIRECTION axis,string color) = 0;//设置轴的颜色
void setOriginPoint(float x,float y,float z) = 0;//设置原点
void setRadius(float radius)=0;//设置半径
void getAxisDirection3D(float& x,float& y,float& z)=0;//获得轴的位置
void setDarkColor(AXISDIRECTION axis, string color) = 0;//设置轴的渐变色
void setLabelVisibility(AXISDIRECTION axis,bool bvisible) = 0;//标注是否可见
void setAxisSize(AXISDIRECTION axis,float size) = 0;//设置轴的大小
@LeonardoTech

**Comment by LeonardoTech** [comment]
全大写单词之间加下划线，不管是什么里的都要这样。

**Comment by LeonardoTech** [comment]
设置的原点是二维平面坐标系

**Comment by LeonardoTech** [comment]
void getAxisDirection3D(float& x,float& y,float& z)=0;//获得轴的位置
这个是获取轴的方向，要指定是哪个轴

**Comment by LeonardoTech** [comment]
void setDarkColor(AXISDIRECTION axis, string color) = 0;//设置轴的渐变色
这个是设置轴渐变色的暗色，要写清楚

**Comment by LeonardoTech** [comment]
void setAxisSize(AXISDIRECTION axis,float size) = 0;//设置轴的大小
这个是设置轴线的宽度，把名称和注释改了

**Comment by luoxin1** [comment]
修改接口：
- void setLabel(AXIS_DIRECTION axis, string label) = 0;//设置标注
- void setLabelPosition(AXIS_DIRECTION axis, float x, float y, float z) = 0;//设置标注出现的位置
- void setColor(AXIS_DIRECTION axis, string color) = 0;//设置轴的颜色
- void setOriginPoint(float x,float y) = 0;//设置原点
- void setRadius(float radius)=0;//设置半径
- void getAxisDirection3D(AXIS_DIRECTION axis,float& x, float& y, float& z) = 0;//获得轴的位置
- void setDarkColor(AXIS_DIRECTION axis, string color) = 0;//设置轴的渐变色的暗色

-void setLabelVisibility(AXIS_DIRECTION axis, bool bvisible) = 0;//设置轴是否可见
-  void setAxisWidth(AXIS_DIRECTION axis, float size) = 0;//设置轴线的宽度
  @LeonardoTech

**Comment by LeonardoTech** [comment]
void setAxisWidth(AXIS_DIRECTION axis, float size) = 0;//设置轴线的
size 改width 就完事儿了

**Comment by luoxin1** [comment]
修改接口:
- void setAxisWidth(AXIS_DIRECTION axis, float width) = 0;//设置轴线的宽度
  @LeonardoTech
